package capability
import("bytes";"crypto/sha256";"encoding/hex";"encoding/json";"errors";"fmt";"io";"os";"path/filepath";"strings")
const(RegistryKind="hq.capabilityRegistry.v1";BindingKind="hq.capabilityBinding.v1";HostOpenCapability="host.open";HostOpenContract="host.open.v1")
type Registry struct{Kind string `json:"kind"`;DeploymentID string `json:"deployment_id"`;Bindings []Binding `json:"bindings"`}
type Binding struct{Kind string `json:"kind"`;CapabilityID string `json:"capability_id"`;ProviderID string `json:"provider_id"`;ContractVersion string `json:"contract_version"`;DeploymentID string `json:"deployment_id"`;ProviderKind string `json:"provider_kind"`;ExecutablePath string `json:"executable_path"`;IntegrityDigest string `json:"integrity_digest"`;VerificationStatus string `json:"verification_status"`;IdempotencyContract string `json:"idempotency_contract,omitempty"`}
func Load(path,expected,capabilityID string)(Binding,error){if !filepath.IsAbs(path){return Binding{},errors.New("capability registry path must be absolute")};f,err:=os.Open(path);if err!=nil{return Binding{},fmt.Errorf("open capability registry: %w",err)};defer f.Close();r,err:=Decode(f);if err!=nil{return Binding{},err};if r.Kind!=RegistryKind{return Binding{},fmt.Errorf("registry kind must be %q",RegistryKind)};if r.DeploymentID!=expected||strings.TrimSpace(expected)==""{return Binding{},errors.New("capability registry deployment identity mismatch")};var selected *Binding;seen:=map[string]struct{}{};for i:=range r.Bindings{b:=&r.Bindings[i];if _,ok:=seen[b.CapabilityID];ok{return Binding{},fmt.Errorf("duplicate capability binding %q",b.CapabilityID)};seen[b.CapabilityID]=struct{}{};if err:=b.Validate(r.DeploymentID);err!=nil{return Binding{},fmt.Errorf("binding %d: %w",i+1,err)};if b.CapabilityID==capabilityID{selected=b}};if selected==nil{return Binding{},fmt.Errorf("capability %q is unavailable",capabilityID)};if err:=selected.VerifyExecutable();err!=nil{return Binding{},err};return *selected,nil}
func Decode(r io.Reader)(Registry,error){data,err:=io.ReadAll(io.LimitReader(r,4<<20));if err!=nil{return Registry{},err};d:=json.NewDecoder(bytes.NewReader(data));d.DisallowUnknownFields();var v Registry;if err:=d.Decode(&v);err!=nil{return Registry{},err};var extra any;if err:=d.Decode(&extra);err!=io.EOF{if err==nil{return Registry{},errors.New("capability registry contains multiple JSON values")};return Registry{},err};return v,nil}
func(b Binding)Validate(expected string)error{if b.Kind!=BindingKind{return fmt.Errorf("kind must be %q",BindingKind)};if b.CapabilityID!=HostOpenCapability{return fmt.Errorf("unsupported capability %q",b.CapabilityID)};if b.ContractVersion!=HostOpenContract{return fmt.Errorf("contract_version must be %q",HostOpenContract)};if b.DeploymentID!=expected{return errors.New("binding deployment identity mismatch")};if strings.TrimSpace(b.ProviderID)==""{return errors.New("provider_id is required")};if b.ProviderKind!="executable"{return errors.New("provider_kind must be executable in v1")};if !filepath.IsAbs(b.ExecutablePath){return errors.New("executable_path must be absolute")};if b.VerificationStatus!="verified"{return errors.New("verification_status must be verified")};return validateDigest(b.IntegrityDigest)}
func(b Binding)VerifyExecutable()error{info,err:=os.Stat(b.ExecutablePath);if err!=nil{return fmt.Errorf("stat provider executable: %w",err)};if !info.Mode().IsRegular(){return errors.New("provider executable is not a regular file")};f,err:=os.Open(b.ExecutablePath);if err!=nil{return err};defer f.Close();h:=sha256.New();if _,err:=io.Copy(h,f);err!=nil{return err};actual:="sha256:"+hex.EncodeToString(h.Sum(nil));if actual!=b.IntegrityDigest{return fmt.Errorf("provider integrity mismatch: expected %s, got %s",b.IntegrityDigest,actual)};return nil}
func validateDigest(v string)error{x:=strings.TrimPrefix(v,"sha256:");if !strings.HasPrefix(v,"sha256:")||len(x)!=64||x!=strings.ToLower(x){return errors.New("integrity_digest must be sha256:<64 lowercase hex chars>")};if _,err:=hex.DecodeString(x);err!=nil{return errors.New("integrity_digest contains invalid hex")};return nil}
