package hqlsp
import("bufio";"crypto/sha256";"encoding/hex";"encoding/json";"errors";"fmt";"io";"os";"strings";"unicode/utf16";"unicode/utf8";"hq/internal/hq";"hq/internal/hqprofile")
const SubmitResultKind="hq.submitResult.v1"
type document struct{Text string;Version int};type Server struct{profile hqprofile.Profile;world *hq.JsonlWorld;documents map[string]document}
func New(p hqprofile.Profile)(*Server,error){f,err:=os.Open(p.WorldPath);if err!=nil{return nil,err};defer f.Close();w,err:=hq.LoadSchemaJSONL(f);if err!=nil{return nil,err};return &Server{profile:p,world:w,documents:map[string]document{}},nil}
func(s *Server)Serve(r io.Reader,w io.Writer)error{br:=bufio.NewReader(r);for{m,err:=readMessage(br);if errors.Is(err,io.EOF){return nil};if err!=nil{return err};if m.Method=="exit"{return nil};if err:=s.handle(w,m);err!=nil{return err}}}
func(s *Server)handle(w io.Writer,m message)error{switch m.Method{case"initialize":return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:map[string]any{"capabilities":map[string]any{"textDocumentSync":1,"completionProvider":map[string]any{"triggerCharacters":[]string{"{","\"",":",","}},"codeActionProvider":true,"executeCommandProvider":map[string]any{"commands":[]string{"hq.submit"}}},"serverInfo":map[string]any{"name":"hq","version":"1"}}});case"initialized":return nil;case"shutdown":return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:nil});case"textDocument/didOpen":var p struct{TextDocument struct{URI string `json:"uri"`;Text string `json:"text"`;Version int `json:"version"`} `json:"textDocument"`};if err:=json.Unmarshal(m.Params,&p);err!=nil{return err};s.documents[p.TextDocument.URI]=document{p.TextDocument.Text,p.TextDocument.Version};return s.publishDiagnostics(w,p.TextDocument.URI);case"textDocument/didChange":var p struct{TextDocument struct{URI string `json:"uri"`;Version int `json:"version"`} `json:"textDocument"`;ContentChanges []struct{Text string `json:"text"`} `json:"contentChanges"`};if err:=json.Unmarshal(m.Params,&p);err!=nil{return err};if len(p.ContentChanges)>0{s.documents[p.TextDocument.URI]=document{p.ContentChanges[len(p.ContentChanges)-1].Text,p.TextDocument.Version};return s.publishDiagnostics(w,p.TextDocument.URI)};return nil;case"textDocument/completion":return s.complete(w,m);case"textDocument/codeAction":return s.codeAction(w,m);case"workspace/executeCommand":return s.executeCommand(w,m);default:if len(m.ID)!=0{return writeError(w,m.ID,-32601,"method not found")};return nil}}
func(s *Server)complete(w io.Writer,m message)error{var p struct{TextDocument struct{URI string `json:"uri"`} `json:"textDocument"`;Position struct{Line int `json:"line"`;Character int `json:"character"`} `json:"position"`};if err:=json.Unmarshal(m.Params,&p);err!=nil{return writeError(w,m.ID,-32602,err.Error())};doc,ok:=s.documents[p.TextDocument.URI];if !ok{return writeError(w,m.ID,-32602,"document is not open")};cursor,err:=byteOffset(doc.Text,p.Position.Line,p.Position.Character);if err!=nil{return writeError(w,m.ID,-32602,err.Error())};suggestions:=hq.Complete(doc.Text,cursor,s.world);items:=make([]map[string]any,0,len(suggestions));for _,x:=range suggestions{items=append(items,map[string]any{"label":x.Label,"detail":x.Detail,"kind":14,"insertText":x.InsertText,"insertTextFormat":1,"data":map[string]any{"compileDraft":x.Draft,"deploymentId":s.profile.DeploymentID}})};return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:map[string]any{"isIncomplete":false,"items":items}})}
func(s *Server)codeAction(w io.Writer,m message)error{uri,err:=uriFromTextDocument(m.Params);if err!=nil{return writeError(w,m.ID,-32602,err.Error())};doc,ok:=s.documents[uri];if !ok{return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:[]any{}})};actions:=[]map[string]any{{"title":"HQ Submit","kind":"quickfix","command":map[string]any{"title":"HQ Submit","command":"hq.submit","arguments":[]any{map[string]any{"uri":uri,"version":doc.Version}}}};return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:actions})}
func(s *Server)executeCommand(w io.Writer,m message)error{var p struct{Command string `json:"command"`;Arguments []struct{URI string `json:"uri"`;Version int `json:"version"`} `json:"arguments"`};if err:=json.Unmarshal(m.Params,&p);err!=nil{return writeError(w,m.ID,-32602,err.Error())};if p.Command!="hq.submit"||len(p.Arguments)!=1{return writeError(w,m.ID,-32602,"hq.submit requires one document argument")};a:=p.Arguments[0];doc,ok:=s.documents[a.URI];if !ok||doc.Version!=a.Version{return writeError(w,m.ID,-32602,"document version is missing or stale")};draft:=hq.CompileLine(doc.Text,s.world);encoded,err:=json.Marshal(draft);if err!=nil{return writeError(w,m.ID,-32603,err.Error())};if err:=appendAndSync(s.profile.AcceptedPath,draft);err!=nil{return writeError(w,m.ID,-32603,err.Error())};sum:=sha256.Sum256(encoded);return writeMessage(w,message{JSONRPC:"2.0",ID:m.ID,Result:map[string]any{"kind":SubmitResultKind,"status":"queued","queueKind":draft.Kind,"queueId":"accepted-sha256-"+hex.EncodeToString(sum[:8]),"deploymentId":s.profile.DeploymentID}})}
func(s *Server)publishDiagnostics(w io.Writer,uri string)error{doc:=s.documents[uri];d:=[]map[string]any{};if x:=strings.TrimSpace(doc.Text);x!=""&&!json.Valid([]byte(x)){d=append(d,map[string]any{"range":map[string]any{"start":map[string]int{"line":0,"character":0},"end":map[string]int{"line":0,"character":utf8.RuneCountInString(doc.Text)}},"severity":1,"source":"hq","code":"invalid-json","message":"buffer is not one complete JSON object"})};return writeMessage(w,message{JSONRPC:"2.0",Method:"textDocument/publishDiagnostics",Params:mustJSON(map[string]any{"uri":uri,"version":doc.Version,"diagnostics":d})})}
func appendAndSync(path string,d hq.CompileDraft)error{f,err:=os.OpenFile(path,os.O_APPEND|os.O_WRONLY,0);if err!=nil{return err};if err:=(hq.QueueWriter{W:f}).Append(d);err!=nil{_ = f.Close();return err};if err:=f.Sync();err!=nil{_ = f.Close();return err};return f.Close()}
func uriFromTextDocument(raw json.RawMessage)(string,error){var p struct{TextDocument struct{URI string `json:"uri"`} `json:"textDocument"`};if err:=json.Unmarshal(raw,&p);err!=nil{return"",err};if p.TextDocument.URI==""{return"",errors.New("textDocument.uri is required")};return p.TextDocument.URI,nil}
func byteOffset(text string,line,character int)(int,error){if line<0||character<0{return 0,errors.New("position cannot be negative")};start:=0;for current:=0;current<line;current++{i:=strings.IndexByte(text[start:],'\n');if i<0{return 0,errors.New("position line is outside document")};start+=i+1};end:=strings.IndexByte(text[start:],'\n');if end<0{end=len(text)-start};part:=text[start:start+end];units,index:=0,0;for index<len(part){r,size:=utf8.DecodeRuneInString(part[index:]);width:=len(utf16.Encode([]rune{r}));if units+width>character{break};units+=width;index+=size;if units==character{return start+index,nil}};if units==character{return start+index,nil};return 0,errors.New("position character is outside document")}
