package hq

import (
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"hq/internal/core"
)

type CommandDiagnostic struct { Line int; Start int; End int; Code string; Message string }
type documentLine struct { Text string; Start int }
type commandObject struct { Name string; StartLine int; EndLine int; Values map[string]string; FieldLines map[string]int }

func commandSuggestions(buffer string, cursor, documentVersion int, world *JsonlWorld, recall *core.WorldRecallIndex) []Suggestion {
	lines := documentLines(buffer); lineIndex, localCursor := lineAtOffset(lines, cursor); line := lines[lineIndex]; before := line.Text[:min(localCursor, len(line.Text))]; trimmed := strings.TrimSpace(before)
	if strings.HasPrefix(trimmed, "@") { name := strings.TrimSpace(strings.TrimPrefix(trimmed, "@")); if _, exact := world.Command(name); !exact { if recall != nil { return recallSuggestions(recall, recall.Recall(core.WorldRecallQuery{Scope: core.WorldRecallObjectQuery, Text: trimmed}), line.Start, line.Start+len(line.Text), trimmed, documentVersion) }; return commandNameSuggestions(world, name, line) }; return nil }
	if !hasCommandHeaderAtOrBefore(lines, lineIndex) { return commandNameSuggestions(world, strings.TrimSpace(strings.TrimPrefix(trimmed, "@")), line) }
	object, err := parseCommandObjectIgnoring(lines, lineIndex, lineIndex); if err != nil { return nil }; definition, ok := world.Command(object.Name); if !ok || lineIndex == object.StartLine { return nil }
	active := strings.TrimSpace(before)
	if key, partial, hasValue := strings.Cut(active, "="); hasValue { field, ok := commandField(definition, strings.TrimSpace(key)); if !ok { return nil }; valueStart := line.Start + strings.Index(line.Text, "=") + 1; clean := strings.Trim(strings.TrimSpace(partial), "\""); if recall != nil { return recallSuggestions(recall, recall.Recall(core.WorldRecallQuery{Scope: core.WorldRecallFieldValue, Text: clean, CommandName: definition.Name, FieldName: field.Name}), valueStart, line.Start+len(line.Text), strings.TrimSpace(partial), documentVersion) }; return commandValueSuggestions(field, clean, valueStart, line.Start+len(line.Text)) }
	partial := strings.TrimSpace(active); present := map[string]bool{}; for field, existingLine := range object.FieldLines { if existingLine != lineIndex { present[field] = true } }
	if recall != nil { return recallSuggestions(recall, recall.Recall(core.WorldRecallQuery{Scope: core.WorldRecallMissingKey, Text: partial, CommandName: definition.Name, PresentFields: present}), line.Start, line.Start+len(line.Text), partial, documentVersion) }
	return commandFieldSuggestions(definition, present, partial, line.Start, line.Start+len(line.Text))
}

func commandNameSuggestions(world *JsonlWorld, partial string, line documentLine) []Suggestion { out:=[]Suggestion{}; for _,command:=range world.Commands { if partial!=""&&!match(command.Name,partial){continue}; insert:="@"+command.Name; out=append(out,Suggestion{Label:command.Name,InsertText:insert,Detail:"hq command object",Description:command.Description,Tag:"command",Score:100,Edit:TextEdit{Start:line.Start,End:line.Start+len(line.Text),Text:insert},Draft:CompileDraft{Kind:"candidate.command",Queue:"instruction.jsonl",Reason:"command declared by profile world"}}) }; sortSuggestions(out); return out }
func commandFieldSuggestions(command CommandDefinition,present map[string]bool,partial string,start,end int)[]Suggestion{out:=[]Suggestion{};for _,field:=range command.Fields{if present[field.Name]||(partial!=""&&!match(field.Name,partial)){continue};insert:=field.Name+"=";out=append(out,Suggestion{Label:field.Name,InsertText:insert,Detail:field.Type,Description:field.Description,Tag:"command field",Score:fieldScore(field),Edit:TextEdit{Start:start,End:end,Text:insert},Draft:CompileDraft{Kind:"candidate.command-field",Queue:"instruction.jsonl",Key:field.Name,Reason:"field declared by profile world"}})};sortSuggestions(out);return out}
func commandValueSuggestions(field CommandField,partial string,start,end int)[]Suggestion{out:=[]Suggestion{};for _,value:=range field.Enum{if partial!=""&&!match(value,partial){continue};insert:=quoteCommandValue(value);out=append(out,Suggestion{Label:value,InsertText:insert,Detail:"value for "+field.Name,Description:field.Description,Tag:"command value",Score:100,Edit:TextEdit{Start:start,End:end,Text:insert},Draft:CompileDraft{Kind:"candidate.command-value",Queue:"instruction.jsonl",Key:field.Name,Value:value,Reason:"value declared by profile world"}})};sortSuggestions(out);return out}

func IsMutableWorldRecall(buffer string,cursor int,world *JsonlWorld)bool{if world==nil||len(world.Commands)==0{return false};if _,selected:=world.SelectedRef();!selected{return false};if buffer==""&&cursor==0{return true};lines:=documentLines(buffer);lineIndex,localCursor:=lineAtOffset(lines,cursor);line:=lines[lineIndex];before:=line.Text[:min(localCursor,len(line.Text))];trimmed:=strings.TrimSpace(before);if strings.HasPrefix(trimmed,"@"){name:=strings.TrimSpace(strings.TrimPrefix(trimmed,"@"));_,exact:=world.Command(name);return !exact};if !hasCommandHeaderAtOrBefore(lines,lineIndex){return false};object,err:=parseCommandObjectIgnoring(lines,lineIndex,lineIndex);if err!=nil{return false};_,exact:=world.Command(object.Name);return exact&&lineIndex!=object.StartLine}

func recallSuggestions(recall *core.WorldRecallIndex,results []core.WorldRecallResult,start,end int,clientPrefix string,documentVersion int)[]Suggestion{out:=make([]Suggestion,0,len(results));mechanicalPrefix:=recallCurrentToken(clientPrefix);for _,result:=range results{edit:=TextEdit{Start:start,End:end,Text:result.Materialization};candidate:=candidateRecord(recall.ID(),documentVersion,result,edit);out=append(out,Suggestion{Label:result.Label,InsertText:result.Materialization,Detail:result.Detail,Description:result.Documentation,Documentation:result.Documentation,Tag:string(result.Kind),Edit:edit,SortText:recallSortText(result.Rank,result.CandidateID),FilterText:strings.TrimSpace(mechanicalPrefix+" "+result.Label),Candidate:&candidate})};return out}
func candidateRecord(indexID string,documentVersion int,result core.WorldRecallResult,edit TextEdit)Candidate{matches:=make([]CandidateMatch,len(result.Matches));for index,match:=range result.Matches{ref:=CandidateSourceRef{TermKind:match.TermKind,TermPath:match.TermPath};matches[index]=CandidateMatch{Token:match.Token,TermKind:match.TermKind,TermPath:match.TermPath,Class:match.Class,Positions:append([]int(nil),match.Positions...),PrimitiveScore:match.PrimitiveScore,SourceRef:ref}};return Candidate{Kind:CandidateKind,CandidateID:result.CandidateID,IndexID:indexID,DocumentVersion:documentVersion,Scope:result.Scope,CandidateKind:result.Kind,Label:result.Label,Detail:result.Detail,Documentation:result.Documentation,World:result.World,Command:result.Command,SourceRefs:candidateSourceRefs(result.StructuralRefs),Matches:matches,Rank:candidateRank(result.Rank),Edit:CandidateEdit{StartByte:edit.Start,EndByte:edit.End,NewText:edit.Text}}}
func recallCurrentToken(input string)string{fields:=strings.Fields(input);if len(fields)==0{return ""};return strings.Trim(strings.TrimPrefix(fields[len(fields)-1],"@"),"\"")}
func recallSortText(rank core.WorldRecallRank,candidateID string)string{values:=[]struct{value int64;descending bool}{{int64(rank.ScopeCompatibility),false},{int64(rank.WorstClass),false},{int64(rank.ExactCount),true},{int64(rank.PrefixCount),true},{int64(rank.SubstringCount),true},{int64(rank.DirectCount),true},{int64(rank.SubsequenceScore),true},{int64(rank.RequiredPreference),true}};if rank.HistoryAware{values=append(values,struct{value int64;descending bool}{int64(rank.SourcePreference),false})};values=append(values,struct{value int64;descending bool}{int64(rank.CandidateKind),false});if rank.HistoryAware{values=append(values,struct{value int64;descending bool}{rank.HistoryRecency,true},struct{value int64;descending bool}{int64(rank.HistoryFrequency),true})};parts:=make([]string,len(values));for index,value:=range values{encoded:=uint64(value.value)^(uint64(1)<<63);if value.descending{encoded=^encoded};parts[index]=fmt.Sprintf("%016x",encoded)};return "rank-"+strings.Join(parts,"-")+"-"+candidateID}

func CompileCommandObject(text string,cursorLine int,world *JsonlWorld)(CompileDraft,error){if world==nil||len(world.Commands)==0{return CompileDraft{},errors.New("profile world has no command definitions")};lines:=documentLines(text);if cursorLine<0||cursorLine>=len(lines){return CompileDraft{},errors.New("submit line is outside document")};object,err:=parseCommandObject(lines,cursorLine);if err!=nil{return CompileDraft{},err};definition,ok:=world.Command(object.Name);if !ok{return CompileDraft{},fmt.Errorf("unknown command %q",object.Name)};for key:=range object.Values{if _,ok:=commandField(definition,key);!ok{return CompileDraft{},fmt.Errorf("unknown field %q for %s",key,definition.Name)}};instruction:=cloneMap(definition.Instruction);for _,field:=range definition.Fields{raw,present:=object.Values[field.Name];if !present{if field.Required{return CompileDraft{},fmt.Errorf("required field %q is missing",field.Name)};continue};value,err:=commandValue(field,raw);if err!=nil{return CompileDraft{},err};if err:=bindValue(instruction,field.Bind,value);err!=nil{return CompileDraft{},fmt.Errorf("field %q: %w",field.Name,err)}};return CompileDraft{Kind:"accepted.instruction",Queue:"instruction.jsonl",Instruction:instruction,Reason:"command object accepted by human"},nil}
func CompileCommandLine(text string,world *JsonlWorld)(CompileDraft,error){return CompileCommandObject(text,0,world)}
func ValidateCommandDocument(text string,world *JsonlWorld)[]CommandDiagnostic{if world==nil||len(world.Commands)==0{return nil};lines:=documentLines(text);out:=[]CommandDiagnostic{};for index:=0;index<len(lines);{trimmed:=strings.TrimSpace(lines[index].Text);if trimmed==""{index++;continue};if strings.HasPrefix(trimmed,"{"){if !json.Valid([]byte(trimmed)){out=append(out,CommandDiagnostic{Line:index,End:len([]rune(lines[index].Text)),Code:"invalid-json",Message:"line is not one complete JSON object"})};index++;continue};if !strings.HasPrefix(trimmed,"@"){out=append(out,CommandDiagnostic{Line:index,End:len([]rune(lines[index].Text)),Code:"missing-command-header",Message:"field is outside an @command object"});index++;continue};end:=nextCommandHeader(lines,index+1);queryName:=strings.TrimSpace(strings.TrimPrefix(trimmed,"@"));if _,exact:=world.Command(queryName);!exact{if commandBlockHasBody(lines,index+1,end){_,err:=CompileCommandObject(text,index,world);if err==nil{err=fmt.Errorf("unknown command %q",queryName)};out=append(out,CommandDiagnostic{Line:index,End:len([]rune(lines[index].Text)),Code:"invalid-command-object",Message:err.Error()})};index=end;continue};if _,err:=CompileCommandObject(text,index,world);err!=nil{out=append(out,CommandDiagnostic{Line:index,End:len([]rune(lines[index].Text)),Code:"invalid-command-object",Message:err.Error()})};index=end};return out}
func commandBlockHasBody(lines []documentLine,from,to int)bool{for index:=from;index<to;index++{if strings.TrimSpace(lines[index].Text)!=""{return true}};return false}
func LineAt(text string,line int)(string,error){lines:=documentLines(text);if line<0||line>=len(lines){return "",errors.New("submit line is outside document")};if strings.TrimSpace(lines[line].Text)==""{return "",errors.New("submit line is empty")};return lines[line].Text,nil}
func documentLines(text string)[]documentLine{raw:=strings.Split(text,"\n");lines:=make([]documentLine,len(raw));offset:=0;for index,line:=range raw{line=strings.TrimSuffix(line,"\r");lines[index]=documentLine{Text:line,Start:offset};offset+=len(raw[index])+1};return lines}
func currentLine(buffer string,cursor int)(string,int){lines:=documentLines(buffer);index,_:=lineAtOffset(lines,cursor);return lines[index].Text,lines[index].Start}
func lineAtOffset(lines []documentLine,offset int)(int,int){if offset<0{offset=0};for index:=len(lines)-1;index>=0;index--{if offset>=lines[index].Start{local:=offset-lines[index].Start;if local>len(lines[index].Text){local=len(lines[index].Text)};return index,local}};return 0,0}
func hasCommandHeaderAtOrBefore(lines []documentLine,line int)bool{for index:=line;index>=0;index--{if strings.HasPrefix(strings.TrimSpace(lines[index].Text),"@"){return true}};return false}
func parseCommandObject(lines []documentLine,cursorLine int)(commandObject,error){return parseCommandObjectIgnoring(lines,cursorLine,-1)}
func parseCommandObjectIgnoring(lines []documentLine,cursorLine,ignoredLine int)(commandObject,error){start:=-1;for index:=cursorLine;index>=0;index--{if strings.HasPrefix(strings.TrimSpace(lines[index].Text),"@"){start=index;break}};if start<0{return commandObject{},errors.New("submit position is outside an @command object")};header:=strings.TrimSpace(lines[start].Text);name:=strings.TrimSpace(strings.TrimPrefix(header,"@"));if name==""||strings.ContainsAny(name," \t=\""){return commandObject{},errors.New("command header must be exactly @name")};end:=nextCommandHeader(lines,start+1);if cursorLine>=end{return commandObject{},errors.New("submit position is outside an @command object")};object:=commandObject{Name:name,StartLine:start,EndLine:end,Values:map[string]string{},FieldLines:map[string]int{}};for index:=start+1;index<end;index++{if index==ignoredLine{continue};line:=strings.TrimSpace(lines[index].Text);if line==""{continue};key,value,ok:=strings.Cut(line,"=");key=strings.TrimSpace(key);value=strings.TrimSpace(value);if !ok||key==""||value==""{return commandObject{},fmt.Errorf("line %d must be key=value",index+1)};if _,duplicate:=object.Values[key];duplicate{return commandObject{},fmt.Errorf("field %q is duplicated",key)};unquoted,err:=unquoteCommandValue(value);if err!=nil{return commandObject{},fmt.Errorf("field %q: %w",key,err)};object.Values[key]=unquoted;object.FieldLines[key]=index};return object,nil}
func nextCommandHeader(lines []documentLine,from int)int{for index:=from;index<len(lines);index++{if strings.HasPrefix(strings.TrimSpace(lines[index].Text),"@"){return index}};return len(lines)}
func unquoteCommandValue(value string)(string,error){if !strings.HasPrefix(value,"\""){if strings.ContainsAny(value," \t"){return "",errors.New("values containing whitespace must be quoted")};return value,nil};if len(value)<2||!strings.HasSuffix(value,"\""){return "",errors.New("unterminated quoted value")};return value[1:len(value)-1],nil}
func commandField(command CommandDefinition,name string)(CommandField,bool){for _,field:=range command.Fields{if field.Name==name{return field,true}};return CommandField{},false}
func commandValue(field CommandField,raw string)(any,error){switch field.Type{case "string","path":return raw,nil;case "enum":for _,candidate:=range field.Enum{if raw==candidate{return raw,nil}};return nil,fmt.Errorf("field %q must be one of %s",field.Name,strings.Join(field.Enum,", "));case "integer":value,err:=strconv.Atoi(raw);if err!=nil{return nil,fmt.Errorf("field %q must be an integer",field.Name)};return value,nil;case "boolean":value,err:=strconv.ParseBool(raw);if err!=nil{return nil,fmt.Errorf("field %q must be true or false",field.Name)};return value,nil;default:return nil,fmt.Errorf("field %q has unsupported type %q",field.Name,field.Type)}}
func bindValue(root map[string]any,path string,value any)error{parts:=strings.Split(path,".");if len(parts)==0{return errors.New("bind path is empty")};current:=root;for _,part:=range parts[:len(parts)-1]{if part==""{return errors.New("bind path contains an empty segment")};next,ok:=current[part];if !ok{child:=map[string]any{};current[part]=child;current=child;continue};child,ok:=next.(map[string]any);if !ok{return fmt.Errorf("bind path %q crosses a non-object",path)};current=child};leaf:=parts[len(parts)-1];if leaf==""{return errors.New("bind path has an empty leaf")};current[leaf]=value;return nil}
func cloneMap(input map[string]any)map[string]any{encoded,_:=json.Marshal(input);var output map[string]any;_=json.Unmarshal(encoded,&output);return output}
func quoteCommandValue(value string)string{if strings.ContainsAny(value," \t"){return `"`+value+`"`};return value}
func fieldScore(field CommandField)int{if field.Required{return 100};return 50}
func min(a,b int)int{if a<b{return a};return b}
